iepc_content_admin_homepage:
    path:     /
    defaults:
        _controller: IEPCContentAdminBundle:ContentAdmin:index


iepc_admin_tinymce_upload:
    path: /tinymce/upload
    defaults:
        _controller: IEPCContentAdminBundle:TinyMCE:upload

iepc_admin_tinymcer_browse:
    path: /tinymce/browse
    defaults:
        _controller: IEPCContentAdminBundle:TinyMCE:browse

iepc_content_admin_section:
    path:     /section
    defaults:
        _controller: IEPCContentAdminBundle:Section:index

iepc_content_admin_section_edit:
    path:     /section/edit/{id}
    defaults:
        _controller: IEPCContentAdminBundle:Section:edit
        id: null

iepc_content_admin_section_delete:
    path:     /section/delete/{id}
    defaults:
        _controller: IEPCContentAdminBundle:Section:delete



iepc_content_admin_webpage:
    path:     /webpage
    defaults:
        _controller: IEPCContentAdminBundle:WebPage:index

iepc_content_admin_webpage_edit:
    path:     /webpage/edit/{id}
    defaults:
        _controller: IEPCContentAdminBundle:WebPage:edit
        id: null

iepc_content_admin_webpage_delete:
    path:     /webpage/delete/{id}
    defaults:
        _controller: IEPCContentAdminBundle:WebPage:delete


iepc_content_admin_content:
    path:     /content
    defaults:
        _controller: IEPCContentAdminBundle:Content:index

iepc_content_admin_content_edit:
    path:     /content/edit/{id}
    defaults:
        _controller: IEPCContentAdminBundle:Content:edit
        id: null