assetic:
    debug: '%kernel.debug%'
    use_controller: true
    bundles: ['IEPCWebsiteBundle']
    java: %java_dir%
    filters:
        cssrewrite: ~
        yui_css:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'
        yui_js:
            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'
        lessphp:
            file: '%kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php'
            apply_to: '\.less$'
