parameters:
    content:
        types:
            - 'IEPC\WebsiteBundle\Entity\Event'
            - 'IEPC\WebsiteBundle\Entity\Page'
            - 'IEPC\WebsiteBundle\Entity\Bulletin'
            - 'IEPC\WebsiteBundle\Entity\Gallery'
            - 'IEPC\WebsiteBundle\Entity\News'
            - 'IEPC\FilesBundle\Entity\Document'
            - 'IEPC\FilesBundle\Entity\DocumentCollection'
        tmp_dir:   'media/_tmp'
        files_dir: 'media/content/{type}/{id}'
    