fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

iepc_security:
    resource: "@IEPCSecurityBundle/Resources/config/routing.yml"
    prefix:   /

iepc_content_admin:
    resource: "@IEPCContentAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

iepc_website:
    resource: "@IEPCWebsiteBundle/Resources/config/routing.yml"
    prefix:   /