fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    #prefix:   /admin
    #host: "%admin_host%"

iepc_admin_bundle:
    resource: "@IEPCAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
    #host: "%admin_host%"

iepc_files_bundle:
    resource: "@IEPCFilesBundle/Resources/config/routing.yml"
    host: "%cdn_host%"

iepc_website_bundle:
    resource: "@IEPCWebsiteBundle/Resources/config/routing.yml"
    prefix:   /
