fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# @todo Use subdomain admin.iepcjalisco.org.mx
iepc_content_admin:
    resource: "@IEPCAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

iepc_website:
    resource: "@IEPCWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

# @todo Use subdomain cdn.iepcjalisco.org.mx
iepc_files:
    resource: "@IEPCFilesBundle/Resources/config/routing.yml"
    prefix:   /files
