iepc_admin_homepage:
    path:     /
    defaults:
        _controller: IEPCAdminBundle:Admin:index

iepc_admin_main:
    path:     /main
    defaults:
        _controller: IEPCAdminBundle:Admin:main

iepc_content_admin_section:
    path:     /sections
    defaults:
        _controller: IEPCAdminBundle:Section:index

iepc_content_admin_section_get:
    path:     /sections/get
    defaults:
        _controller: IEPCAdminBundle:Section:get

iepc_content_admin_section_edit:
    path:     /sections/edit/{id}
    defaults:
        _controller: IEPCAdminBundle:Section:edit
        id: null

#**********************************************************************************************************************#

iepc_admin_tinymce_upload:
    path: /tinymce/upload
    defaults:
        _controller: IEPCAdminBundle:TinyMCE:upload

#iepc_admin_tinymcer_browse:
#    path: /tinymce/browse
#    defaults:
#        _controller: IEPCAdminBundle:TinyMCE:browse

iepc_website_admin_content_page:
    path:     /admin/content/page/edit/{id}
    defaults:
        _controller: IEPCWebsiteBundle:Page:edit
        id: null






iepc_content_admin_section_delete:
    path:     /section/delete/{id}
    defaults:
        _controller: IEPCAdminBundle:Section:delete

iepc_content_admin_webpage:
    path:     /webpage
    defaults:
        _controller: IEPCAdminBundle:WebPage:index

iepc_content_admin_webpage_edit:
    path:     /webpage/edit/{id}
    defaults:
        _controller: IEPCAdminBundle:WebPage:edit
        id: null

iepc_content_admin_webpage_delete:
    path:     /webpage/delete/{id}
    defaults:
        _controller: IEPCAdminBundle:WebPage:delete

iepc_content_admin_content:
    path:     /content
    defaults:
        _controller: IEPCAdminBundle:Content:index

iepc_content_admin_content_edit:
    path:     /content/edit/{id}
    defaults:
        _controller: IEPCAdminBundle:Content:edit
        id: null