iepc_website_homepage:
    path:     /
    defaults: { _controller: IEPCContentBundle:WebPage:renderPath }

iepc_website_content:
    path:     /{path}
    defaults: { _controller: IEPCContentBundle:WebPage:renderPath }
    requirements:
        path: .+